image: buildkite/puppeteer:latest

before_script:
  - npm install

cache:
  paths:
    - node_modules/
    - .thumbnails/

pages:
  script:
    - npm run generate-quiet
  artifacts:
    paths:
      - public
  only:
    - master
